clean: true
objc: true
umbrella_header: caraml-core/caraml_core.h
framework_root: caraml-core
sdk: iphonesimulator
module: caraml-core
module_version: 0.1.0
author: LiquidPlayer
author_url: https://github.com/LiquidPlayer
github_url: https://github.com/LiquidPlayer/caraml-core
copyright: © 2019 LiquidPlayer
hide_documentation_coverage: true
output: ../../LiquidPlayer.github.io/caraml-core/0.1.0
root_url: https://liquidplayer.github.io/caraml-core/0.1.0